apiVersion: v2
name: powerdns
description: extendet powerdns chart
type: application
version: 1.3.4
sources:
  - https://github.com/k8s-at-home/charts/tree/master/charts/stable/powerdns

dependencies:
  - name: powerdns
    version: 4.1.2
    repository: https://k8s-at-home.com/charts
  - name: argo-workflow-mixin
    repository: https://nolte.github.io/helm-charts-repo/
    version: 0.4.3
    alias: argo-workflows-execution
