argo-workflows-execution:
  cmTfStaticEndpoints:
    create: true

  role:
    tfState:
      create: false
      name: argo-workflows-execution
    type: ClusterRole
    vaultInjector:
      create: false
      name: argo-workflows-execution
  roleBinding:
    tfState:
      create: true
    type: Role
    vaultInjector:
      create: true
  serviceAccount:
    create: true

  configurationWorkflows:
    post-install:
      type: terragrunt
      workflow: true
      terraform:
        action: apply
      extraAnnotations:
        # Load a Secret for Terraform State file access
        vault.hashicorp.com/agent-inject-secret-pdnsaccess: secrets-tf/services/dns/users/root
        vault.hashicorp.com/agent-inject-template-pdnsaccess: |
          {{- with secret "secrets-tf/services/dns/users/root" -}}
          export PDNS_API_KEY={{ .Data.data.token }}
          {{- end }}
      extraSourceElements:
        - "source /vault/secrets/pdnsaccess"
      extraEnv:
        - name: PDNS_SERVER_URL
          value: http://powerdns-webserver.{{.Release.Namespace}}.svc:8081
      source:
        repo: https://github.com/nolte/argo-charts.git
        path: ./src/applications/powerdns/configuration/baseline
        revision: master
