certmanagerwebhookduckdns:
  fullnameOverride: cert-manager-webhook-duckdns
  clusterIssuer:
    staging:
      create: true
    production:
      create: true
  secret:
    existingSecret: true
    existingSecretName: duckdns-token

externalsecrets:
  enabled: true
  secretstore:
    create: true
    serviceAccount:
      create: true
  secrets:
    duckdns-token:
      data:
        - key: third-party-services/duckdns.org/api
          name: token
          property: token
