certmanagerwebhookduckdns:
  fullnameOverride: cert-manager-webhook-duckdns
  clusterIssuer:
    staging:
      create: true
    production:
      create: true
  secret:
    existingSecret: true
    existingSecretName: duckdns-token

externalsecrets:
  enabled: true
  secrets:
    duckdns-token:
      data:
        - key: secrets-tf/data/third-party-services/duckdns.org/api
          name: token
          property: token  