remote: origin
target-branch: main
helm-extra-args: --timeout 600s
chart-dirs:
- charts/incubator
- charts/stable
excluded-charts:
- charts/stable/external-secrets-manifests
chart-repos:
- bitnami=https://charts.bitnami.com/bitnami
- k8s-at-home-libraries=https://library-charts.k8s-at-home.com
- k8s-at-home=https://k8s-at-home.com/charts
- jetstack=https://charts.jetstack.io
