remote: origin
target-branch: main
helm-extra-args: --timeout 600s
validate-maintainers: false
chart-dirs:
- charts/incubator
- charts/stable
excluded-charts: []
chart-repos:
- bitnami=https://charts.bitnami.com/bitnami
- codecentric=https://codecentric.github.io/helm-charts
- gitea=https://dl.gitea.io/charts/
- hashicorp=https://helm.releases.hashicorp.com
- jetstack=https://charts.jetstack.io
- k8s-at-home-libraries=https://library-charts.k8s-at-home.com
- k8s-at-home=https://k8s-at-home.com/charts
- nolte-charts=https://nolte.github.io/helm-charts-repo
- nolte-ebrianne=https://nolte.github.io/ebrianne-helm-charts
