#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: nolte/snapcast-server
  # -- image tag
  tag: v0.26.0
  # -- image pull policy
  pullPolicy: IfNotPresent

controller:
  strategy: Recreate
  
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC

snapcastServer:
  config: |
    [http]
    doc_root = /usr/share/snapserver/snapweb
    
    [stream]
    stream = tcp://0.0.0.0:4953?name=mopidy_tcp

#- mountPath: /root/.config/snapcast/
# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    enabled: true
    ports:
      http:
        enabled: true
        protocol: TCP
        port: 1780
      stream:
        enabled: true
        protocol: TCP
        port: 4953
  public:
    type: NodePort
    enabled: true
    ports:
      control:
        enabled: true
        protocol: TCP
        port: 1704    
        nodePort: 30704
      server:
        enabled: true
        protocol: TCP
        port: 1705
        nodePort: 30705

# -- Override the command(s) for the default container
args: ["-c","/tmp/snapserver/snapserver.conf"]
# -- Override the args for the default container
#args: []


persistence:
  snapserver-config:
    name: snapserver-config
    # -- Enables or disables the persistence item
    enabled: true
    mountPath: /tmp/snapserver/
    type: configMap    