---
repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
        exclude: "charts/stable/*.*/README.md"

      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md']
