---
repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
        exclude: |
          (?x)(
              .md|
              .bumpversion.cfg
          )
