homeassistant:
  global:
    fullnameOverride: home-assistant

  envFrom:
    - secretRef:
        name: home-assistant-creds

  controller:
    annotations:
      reloader.stakater.com/auto: "true"

  additionalContainers:
    hassConfigurator:
      image: causticlab/hass-configurator-docker:latest
      name: hass-configurator
      volumeMounts:
        - mountPath: /hass-config
          name: config
        - mountPath: /root/.ssh
          name: gitsecret
  resources:
    limits:
      cpu: 2
      memory: 2048Mi
    requests:
      cpu: 1
      memory: 1024Mi
  persistence:
    gitsecret:
      enabled: true
      mountPath: /root/.ssh
      type: custom
      volumeSpec:
        secret:
          defaultMode: 256
          optional: true
          secretName: git-creds
    config:
      enabled: true
      mountPath: /config

  ingress:
    main:
      enabled: false
      ingressClassName: nginx
      annotations:
        nginx.org/websocket-services: home-assistant
      hosts:
        - host: "home-assistant.local"
          paths:
            - path: /

certificate:
  create: false

externalsecrets:
  enabled: false

httpProxy:
  create: false
  fqdn: home-assistant.smart-home.k8sservices.local
  tls:
    secretName: cert-manager/wildcard-duckdns-org-tls
