homeassistant:
  initContainers:
    gitsync:
      args:
      - set -e; if [ -d "/config/.git" ]; then git -C "/config" pull || true; else if
        [ "$(ls -A /config)" ]; then git clone --branch ${GIT_BRANCH} --depth 2 "${GIT_REPO}"
        /tmp/repo; cp -rf /tmp/repo/.git "/config"; cd "/config"; git checkout -f; else
        git clone --branch ${GIT_BRANCH} --depth 2 "${GIT_REPO}" "/config";
        fi; fi; if [ -f "/root/.ssh/git-crypt-key" ]; then cd /config; git-crypt unlock
        "/root/.ssh/git-crypt-key"; fi;
      env:
        - name: "GIT_BRANCH"
          value: "feature/minimized-config"
        - name: "GIT_REPO"
          value: "git@github.com:nolte/home-assistant-config.git"
      command:
      - /bin/sh
      - -c
      image: k8sathome/git-crypt:2020.11.15
      imagePullPolicy: IfNotPresent
      name: git-sync
      volumeMounts:
      - mountPath: /config
        name: config
      - mountPath: /root/.ssh
        name: gitsecret