homeassistant:
  podSecurityContext:
    fsGroup: 1000
  persistence:
    shared:
      enabled: true
      type: emptyDir

  initContainers:
    gitsync:
      name: init
      image: k8s.gcr.io/git-sync/git-sync:v3.5.0
      stdin: true
      stdinOnce: true
      tty: true
      env:
      - name: GIT_SYNC_ONE_TIME
        value: 'true'
      - name: GIT_SYNC_ADD_USER
        value: 'true'
      - name: GIT_SYNC_REPO
        value: git@github.com:nolte/home-assistant-config.git
      - name: GIT_SYNC_BRANCH
        value: feature/sparse-checkout
      - name: GIT_SYNC_ROOT
        value: "/tmp/repo"
      - name: GIT_SYNC_DEST
        value: current
      - name: GIT_SYNC_DEPTH
        value: '1'
      - name: GIT_SYNC_SSH
        value: 'true'
      - name: GIT_SSH_KEY_FILE
        value: "/tmp/ssh-key/id_rsa"
      - name: GIT_SSH_KNOWN_HOSTS_FILE
        value: "/tmp/ssh-key/known_hosts"
      volumeMounts:
      - mountPath: "/tmp/ssh-key"
        name: gitsecret
      - mountPath: "/tmp/repo"
        name: shared
    xcopy:
      name: copy
      image: busybox:latest
      args:
      - cp
      - "-rf"
      - "-L"
      - "-a"
      - "/tmp/repo/current/src/."
      - "/config/"
      stdin: true
      stdinOnce: true
      tty: true
      volumeMounts:
      - mountPath: "/tmp/repo"
        name: shared
      - mountPath: "/config"
        name: config
