gitCreds:
  create: true

assistantCreds:
  create: true
  data:
    - key: secrets-tf/data/third-party-services/google.com/projects/home-assistant
      name: GOOGLE_CLIENT_ID
      property: client_id

    - key: secrets-tf/data/third-party-services/google.com/projects/home-assistant
      name: GOOGLE_CLIENT_SECRET
      property: client_secret

    - key: secrets-tf/data/third-party-services/openweathermap.org/projects/home-assistant
      name: OPENWEATHERMAP_API_KEY
      property: token

    - key: secrets-tf/data/services/router-fritz-box/users/admin
      name: FRITZBOX_USERNAME
      property: username
    - key: secrets-tf/data/services/router-fritz-box/users/admin
      name: FRITZBOX_PASSWORD
      property: password

    - key: secrets-tf/data/third-party-services/github.com/apitoken/home-assistant
      name: GITHUB_ACCESS_TOKEN
      property: token

#    - key: secrets-tf/data/third-party-services/github.com/deploymentkey/home-assistant
#      name: TELEGRAM_API_TOKEN
#      property: token
#    - key: secrets-tf/data/third-party-services/github.com/deploymentkey/home-assistant
#      name: TELEGRAM_USER_ID
#      property: token
#    - key: secrets-tf/data/third-party-services/github.com/deploymentkey/home-assistant
#      name: TELEGRAM_CHAT_ID
#      property: token
