{{- include "common.values.setup" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: mopidy-config
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  mopidy.conf: |
    {{- tpl .Values.mopidy.config . | nindent 4 }}
