# Default values for external-secrets-manifests.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

secrets: {}
#  test-secret-one:
#    data:
#      - key: secrets-tf/data/third-party-services/duckdns.org/api
#        name: token
#        property: token
