# Default values for external-secrets-manifests.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

secretstore:
  create: false
  path: secrets-tf
  server: "http://vault.vault.svc:8200"
  role: external-secrets
  mountPath: kubernetes
  serviceAccount:
    create: false
    name: external-secrets

secrets: {}
#  test-secret-one:
#    data:
#      - key: secrets-tf/data/third-party-services/duckdns.org/api
#        name: token
#        property: token
