apiVersion: v2
name: keycloak
description: Preconfigured keycloak Deployment
type: application
version: 2.0.2
sources:
  - https://codecentric.github.io/helm-charts
  - https://github.com/codecentric/helm-charts/tree/master/charts/keycloak
dependencies:
  - name: keycloak
    version: 17.0.3
    repository: https://codecentric.github.io/helm-charts
  - name: argo-workflow-mixin
    repository: https://nolte.github.io/helm-charts-repo/
    version: 0.2.0
    alias: argo-workflows-execution
