apiVersion: v2
dependencies:
  - name: external-dns
    repository: https://charts.bitnami.com/bitnami
    version: 6.2.4
    alias: externalDns
description: Wrapped External DNS deployment, with External Secrets Support.
name: external-dns
sources:
  - https://artifacthub.io/packages/helm/bitnami/external-dns
  - https://github.com/bitnami/charts/tree/master/bitnami/external-dns
type: application
version: 0.0.1
