externaldns:
  pdns:
    apiUrl: http://powerdns-webserver.powerdns.svc
    secretName: pdns-access

  provider: pdns

externalsecrets:
  enabled: false
  secretstore:
    create: true
    serviceAccount:
      create: true
  secrets:
    pdns-access:
      data:
        - key: services/dns/users/root
          name: pdns_api_key
          property: token
