
{{- $dot := . -}}
{{- range $k, $v := .Values.configurationWorkflows }}
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{$k}}
  labels:
    {{- include "argo-workflows-execution.labels" $dot | nindent 4 }}
spec:
  entrypoint: exec
  arguments:
    parameters:
    - name: revision
      value: "{{ $v.source.revision }}" #master
    - name: action
      value: {{ $v.terraform.action }}
    - name: path
      value: {{ $v.source.path }}

  templates:
  - name: exec
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "argo-workflows"
        vault.hashicorp.com/agent-inject-token: "true"
        # Load a Secret for Terraform State file access
        vault.hashicorp.com/agent-inject-secret-pdnsaccess: secrets-tf/services/dns/users/root
        vault.hashicorp.com/agent-inject-template-pdnsaccess: |
          {{"{{-"}} with secret "secrets-tf/services/dns/users/root" {{ "-}}" }}
          export PDNS_API_KEY={{"{{"}} .Data.data.token {{ "}}" }}
          {{"{{-"}} end {{ "}}" }}
        vault.hashicorp.com/agent-inject-secret-s3access: secrets-tf/services/s3/users/admin
        vault.hashicorp.com/agent-inject-template-s3access: |
          {{"{{-"}} with secret "secrets-tf/services/s3/users/admin" {{ "-}}" }}
          [default]
          aws_access_key_id={{"{{"}} .Data.data.accesskey {{ "}}" }}
          aws_secret_access_key={{"{{"}} .Data.data.secretkey {{ "}}" }}
          {{"{{-"}} end {{ "}}" }}
    inputs:
      parameters:
      - name: revision
        value: "{{ $v.source.revision }}" #master
      - name: action
        value: {{ $v.terraform.action }}
      - name: path
        value: {{ $v.source.path }}
      artifacts:
      - name: argo-source
        path: "/src"
        git:
          repo: "{{ $v.source.repo }}"
          revision: "{{ "{{" }}inputs.parameters.revision{{ "}}" }}"
    script:
      image: alpine/terragrunt
      command: [bash]
      workingDir: "/src"
      source: |
        #!/usr/bin/env bash
        set -o errexit
        set -o pipefail
        set -o nounset
        cd {{ "{{" }}inputs.parameters.path{{ "}}" }}
        source /vault/secrets/pdnsaccess
        export VAULT_TOKEN=$(cat /vault/secrets/token)
        terragrunt {{ "{{" }}inputs.parameters.action{{ "}}" }} -input=false -auto-approve -no-color

      env:
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /vault/secrets/s3access
        {{- range $index, $var := $v.extraEnv }}
        - name: {{ tpl $var.name $dot}}
          value: {{ tpl $var.value $dot}}
        {{- end }}
      envFrom:
        - configMapRef:
            name: tf-static-endpoints
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: {{$k}}
  labels:
    {{- include "argo-workflows-execution.labels" $dot | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/hook: PostSync
spec:
  entrypoint: exec
  templates:
  - name: exec
    steps:
      - - name: configure-service
          templateRef:
            name: {{$k}}
            template: exec

{{- end -}}