
{{- include "common.values.setup" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: snapserver-config
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  snapserver.conf: |
    {{- tpl .Values.snapcastServer.config . | nindent 4 }}
