{{- $dot := . }}
{{- range $k, $v := $dot.Values.secrets }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ tpl $k $dot }}
  labels:
    {{- include "external-secrets-manifests.labels" $dot | nindent 4 }}
spec:
  backendType: {{ $v.backendType | default "vault" }}
  {{- with $v.data }}
  data:
    {{- range $secretDataElement := . }}
    - key: {{ tpl $secretDataElement.key $dot }}
      name: {{ tpl $secretDataElement.name $dot }}
      property: {{ tpl $secretDataElement.property $dot }}
    {{ end }}
  {{- end }}
{{- end }}