{{- $dot := . }}
{{- range $k, $v := $dot.Values.secrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ tpl $k $dot }}
  labels:
    {{- include "external-secrets-manifests.labels" $dot | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: {{ tpl $k $dot }}
    creationPolicy: Owner
  {{- with $v.data }}
  data:
    {{- range $secretDataElement := . }}
    - secretKey: {{ tpl $secretDataElement.name $dot }}
      remoteRef:
        key: {{ tpl $secretDataElement.key $dot }}
        property: {{ tpl $secretDataElement.property $dot }}
    {{ end }}
  {{- end }}
{{- end }}
