{{- $dot := . }}
{{- if and .Values.secretstore.create  .Values.secretstore.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ $dot.Values.secretstore.serviceAccount.name }}"
  labels:
    {{- include "external-secrets-manifests.labels" $dot | nindent 4 }}
{{- end }}
