{{- $dot := . }}
{{- if .Values.secretstore.create }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  labels:
    {{- include "external-secrets-manifests.labels" $dot | nindent 4 }}
spec:
  provider:
    vault:
      server: "{{ $dot.Values.secretstore.server }}"
      path: "{{ $dot.Values.secretstore.path }}"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "{{ $dot.Values.secretstore.mountPath }}"
          role: "{{ $dot.Values.secretstore.role }}"
          serviceAccountRef:
            name: "{{ $dot.Values.secretstore.serviceAccount.name }}"
{{- end }}
