apiVersion: v2
dependencies:
  - name: gitea
    repository: https://dl.gitea.io/charts/
    version: 5.0.4
description: Preconfigured gitea Deployment
name: gitea
sources:
  - https://gitea.com/gitea/helm-chart
  - https://gitea.io/en-us/
type: application
version: 1.1.2
