apiVersion: v2
dependencies:
  - name: gitea
    repository: https://dl.gitea.io/charts/
    version: 5.0.8
  - name: external-secrets-manifests
    version: 0.1.3
    repository: https://nolte.github.io/helm-charts-repo/
    alias: externalsecrets
    condition: externalsecrets.enabled
description: Preconfigured gitea Deployment
name: gitea
sources:
  - https://gitea.com/gitea/helm-chart
  - https://gitea.io/en-us/
type: application
version: 1.2.6
