fullnameOverride: ''
nameOverride: ''

cmTfStaticEndpoints:
  create: false
  s3: http://minio.minio.svc
  vaultEndpoint: http://vault.vault.svc:8200
  keycloak: http://keycloak-http.keycloak.svc

role:
  tfState:
    create: false
    name: argo-workflows-execution
  type: ClusterRole
  vaultInjector:
    create: false
    name: argo-workflows-execution

roleBinding:
  tfState:
    create: false
  type: Role
  vaultInjector:
    create: false

serviceAccount:
  annotations: {}
  create: false
  name: argo-workflows-executer

configurationWorkflows: {}
#  post-install:
#    type: terragrunt
#    workflow: true
#    terraform:
#      action: apply
#    extraEnv:
#      - name: PDNS_SERVER_URL
#        value: http://powerdns-webserver.{{.Release.Namespace}}.svc:8081
#    source:
#      repo: https://github.com/nolte/argo-charts.git
#      path: ./src/applications/powerdns/configuration/baseline
#      revision: master
