fullnameOverride: ''
nameOverride: ''

cmTfStaticEndpoints:
  create: false
  s3: http://minio.minio.svc
  vaultEndpoint: http://vault.vault.svc:8200
  keycloak: http://keycloak.keycloak.svc

global:
  argocd:
    hook: PostSync
  workflow:
    terragrunt:
      # -- Default terragrunt Container version
      image: alpine/terragrunt:1.9.8

role:
  tfState:
    create: false
    name: argo-workflows-execution
  type: ClusterRole
  vaultInjector:
    create: false
    name: argo-workflows-execution
  executor:
    create: false
    name: argo-workflows-execution

roleBinding:
  tfState:
    create: false
  type: Role
  vaultInjector:
    create: false
  executor:
    create: false

serviceAccount:
  annotations: {}
  create: false
  name: argo-workflows-executer

configurationWorkflows: {}
#  post-install:
#    type: terragrunt
#    workflow: true
#    terraform:
#      action: apply
#    extraAnnotations:
#      # Load a Secret for Terraform State file access
#      vault.hashicorp.com/agent-inject-secret-pdnsaccess: secrets-tf/services/dns/users/root
#      vault.hashicorp.com/agent-inject-template-pdnsaccess: |
#        {{- with secret "secrets-tf/services/dns/users/root" -}}
#        export PDNS_API_KEY={{ .Data.data.token }}
#        {{- end }}
#    extraEnv:
#      - name: PDNS_SERVER_URL
#        value: http://powerdns-webserver.{{.Release.Namespace}}.svc:8081
#    source:
#      repo: https://github.com/nolte/argo-charts.git
#      path: ./src/applications/powerdns/configuration/baseline
#      revision: master
