fullnameOverride: ''
nameOverride: ''

cmTfStaticEndpoints:
  create: true
  s3: http://minio.minio.svc
  vaultEndpoint: http://vault.vault.svc:8200
  keycloak: http://keycloak-http.keycloak.svc


role:
  tfState:
    create: true
    name: argo-workflows-execution
  type: ClusterRole
  vaultInjector:
    create: true
    name: argo-workflows-execution

roleBinding:
  tfState:
    create: true
  type: Role
  vaultInjector:
    create: false

serviceAccount:
  annotations: {}
  create: true
  name: argo-workflows-executer

configurationWorkflows:
  post-install:
    type: bash
    workflow: true

    script:
      image: alpine/terragrunt:latest
      source: |-
        echo "hallo"
        echo Whats Up
    terraform:
      action: apply      
    extraAnnotations:
      # Load a Secret for Terraform State file access
      vault.hashicorp.com/agent-inject-secret-pdnsaccess: secrets-tf/services/dns/users/root
      vault.hashicorp.com/agent-inject-template-pdnsaccess: |
        {{- with secret "secrets-tf/services/dns/users/root" -}}
        export PDNS_API_KEY={{ .Data.data.token }}
        {{- end }}
    extraEnv:
      - name: PDNS_SERVER_URL
        value: http://powerdns-webserver.{{.Release.Namespace}}.svc:8081
    source:
      repo: https://github.com/nolte/argo-charts.git
      path: ./src/applications/powerdns/configuration/baseline
      revision: master
    extraEnvFrom: 
      - secretRef:
          name: harbor-admin
      - secretRef:
          name: harbor-admin          
  post-sync:
    type: terragrunt
    workflow: true
    script:
      image: alpine/terragrunt:latest
    terraform:
      action: apply
    extraAnnotations:
      # Load a Secret for Terraform State file access
      vault.hashicorp.com/agent-inject-secret-pdnsaccess: secrets-tf/services/dns/users/root
      vault.hashicorp.com/agent-inject-template-pdnsaccess: |
        {{- with secret "secrets-tf/services/dns/users/root" -}}
        export PDNS_API_KEY={{ .Data.data.token }}
        {{- end }}
    extraEnv:
      - name: PDNS_SERVER_URL
        value: http://powerdns-webserver.{{.Release.Namespace}}.svc:8081
    source:
      repo: https://github.com/nolte/argo-charts.git
      path: ./src/applications/powerdns/configuration/baseline
      revision: master
