apiVersion: v2
appVersion: v0.0.1
description: Hackable Music Server
name: mopidy
version: 0.3.1
kubeVersion: ">=1.16.0-0"
keywords:
- fritz-exporter
- fritzbox
home: https://github.com/nolte/helm-charts-repo/tree/master/charts/stable/mopidy
sources:
- https://github.com/mopidy/mopidy
- https://mopidy.com/
- https://github.com/wernight/docker-mopidy
maintainers: []
dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 4.5.2
