args:
  - -o 
  - spotify/username=$(SPOTIFY_USERNAME) 
  - -o 
  - spotify/password=$(SPOTIFY_PASSWORD) 
  - -o 
  - spotify/client_id=$(SPOTIFY_CLIENT_ID) 
  - -o 
  - spotify/client_secret=$(SPOTIFY_CLIENT_SECRET)

envFrom:
  - secretRef:
      name: spotify-auth

mopidy:
  snapcast:
    server:
      host: snapcast-server
  spotify:
    enabled: true
