#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: nolte/snapcast-client
  # -- image tag
  tag: v0.26.0
  # -- image pull policy
  pullPolicy: IfNotPresent

controller:
  strategy: Recreate

securityContext:
  privileged: true  

# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC

#- mountPath: /root/.config/snapcast/
# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    enabled: false

# -- Override the command(s) for the default container
args: ["-h", "rpi-snapcast-server"]

persistence:
  hostpathmounts-data:
      enabled: true
      type: hostPath
      hostPath: "/dev/snd"
      mountPath: "/dev/snd"

nodeSelector:
  task: hifi

